name: Set up Poetry
description: |
  Instrument Poetry and Poe the Poet CLIs.

inputs:
  python-version:
    description: "Used python version"
    required: true

runs:
  using: composite
  steps:
    - name: Install poetry
      shell: bash
      run: |
        pipx install poetry
        # and the task runner
        pipx inject poetry poethepoet --include-apps
    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"
