name: Analyze
description: |
  Scan Python code statically.
  Invoking:
    - type-checker
    - linter

runs:
  using: composite
  steps:
    - name: Type-check
      shell: bash
      run: |
        uvx --from poethepoet poe types
    - name: Lint
      shell: bash
      run: |
        uvx --from poethepoet poe lint
        uvx --from poethepoet poe lint-warnings
