name: Analyze
description: |
  Scan Python code statically.
  Invoking:
    - type-checker
    - linter

runs:
  using: composite
  steps:
    - name: Type-check
      shell: bash
      run: |
        uv run --with poethepoet poe types
    - name: Lint
      shell: bash
      run: |
        uv run --with poethepoet poe lint
        uv run --with poethepoet poe lint-warnings
