name: Analysis

on:
  workflow_call:
    inputs:
      types:
        description: "Enable type check"
        required: false
        type: boolean
        default: true

jobs:
  analyse:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install and configure poetry
        uses: snok/install-poetry@v1
      - name: Load cached venv
        id: analysis
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: >-
            ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}
            -${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with-analysis
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Install task runner
        run: pip install poethepoet
      - name: Lint
        run: |
          poe lint
          poe lint-warnings
      - name: Type check
        if: ${{ inputs.types }}
        run: |
          poe mypy
