name: Build the documentation

on:
  workflow_call:
    inputs:
      python-version:
        description: "Used python version"
        required: true
        type: string
      uv-extras:
        description: "uv sync extra flags"
        required: false
        type: string
        default: ""
      output-path:
        description: "docs output location"
        required: true
        type: string

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: qiboteam/workflows/actions/uv/setup@uv
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install project
        run: uv sync ${{ inputs.uv-extras }}
      - name: Install dependencies and compile the documentation
        run: |
          sudo apt install pandoc
          uv run --no-dev --with poethepoet poe docs
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ${{ inputs.output-path }}
