name: Tests

on:
  workflow_call:
    inputs:
      os:
        description: "Used operation system"
        required: true
        type: string
      python-version:
        description: "Used python version"
        required: true
        type: string
      uv-extras:
        description: "uv sync extra flags"
        required: false
        type: string
        default: ""
      doctests:
        description: "Enable examples test"
        required: false
        type: boolean
        default: false
    secrets:
      codecov_token:
        required: false

defaults:
  run:
    shell: bash

jobs:
  analyze:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: qiboteam/workflows/actions/uv/setup@uv
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install project
        run: uv sync ${{ inputs.uv-extras }}
      - uses: qiboteam/workflows/actions/uv/analyze@uv

  test:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: qiboteam/workflows/actions/uv/setup@uv
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install project
        run: uv sync ${{ inputs.uv-extras }}
      - uses: qiboteam/workflows/actions/uv/test@uv
        with:
          doctests: ${{ toJSON(inputs.doctests) }}
          codecov_token: ${{ secrets.codecov_token }}
